# Generated by Django 6.0.6 on 2026-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0007_widen_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
